
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDSUBleftMULDIVrightNEGnonassocPOWADD DIV ENDL LPAREN MUL NUM POW RPAREN SUBline : expr ENDLline : error ENDLexpr : numberexpr : LPAREN expr RPARENexpr : SUB LPAREN expr RPAREN %prec NEGexpr : expr ADD exprexpr : expr SUB exprexpr : expr MUL exprexpr : expr POW exprPowexpr : expr DIV exprnumber : NUMnumber : SUB number %prec NEGexprPow : numberPowexprPow : LPAREN exprPow RPARENexprPow : SUB LPAREN exprPow RPAREN %prec NEGexprPow : exprPow ADD exprPowexprPow : exprPow SUB exprPowexprPow : exprPow MUL exprPowexprPow : exprPow DIV exprPownumberPow : NUMnumberPow : SUB numberPow %prec NEG'
    
_lr_action_items = {'error':([0,],[3,]),'LPAREN':([0,5,6,9,10,11,12,13,17,24,25,30,31,32,33,36,],[5,5,17,5,5,5,24,5,5,24,36,24,24,24,24,24,]),'SUB':([0,2,4,5,6,7,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,],[6,10,-3,6,16,-11,6,6,6,25,6,10,16,6,-12,-6,-7,-8,-9,-13,25,35,-20,-10,-4,10,25,25,25,25,31,35,25,-21,-5,-16,-17,-18,-19,-14,31,-15,]),'NUM':([0,5,6,9,10,11,12,13,16,17,24,25,30,31,32,33,35,36,],[7,7,7,7,7,7,26,7,7,7,26,26,26,26,26,26,26,26,]),'$end':([1,8,14,],[0,-1,-2,]),'ENDL':([2,3,4,7,18,19,20,21,22,23,26,27,28,37,38,39,40,41,42,43,45,],[8,14,-3,-11,-12,-6,-7,-8,-9,-13,-20,-10,-4,-21,-5,-16,-17,-18,-19,-14,-15,]),'ADD':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,34,37,38,39,40,41,42,43,44,45,],[9,-3,-11,9,-12,-6,-7,-8,-9,-13,-20,-10,-4,9,30,-21,-5,-16,-17,-18,-19,-14,30,-15,]),'MUL':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,34,37,38,39,40,41,42,43,44,45,],[11,-3,-11,11,-12,11,11,-8,-9,-13,-20,-10,-4,11,32,-21,-5,32,32,-18,-19,-14,32,-15,]),'POW':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,37,38,39,40,41,42,43,45,],[12,-3,-11,12,-12,12,12,12,-9,-13,-20,12,-4,12,-21,-5,-16,-17,-18,-19,-14,-15,]),'DIV':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,34,37,38,39,40,41,42,43,44,45,],[13,-3,-11,13,-12,13,13,-8,-9,-13,-20,-10,-4,13,33,-21,-5,33,33,-18,-19,-14,33,-15,]),'RPAREN':([4,7,15,18,19,20,21,22,23,26,27,28,29,34,37,38,39,40,41,42,43,44,45,],[-3,-11,28,-12,-6,-7,-8,-9,-13,-20,-10,-4,38,43,-21,-5,-16,-17,-18,-19,-14,45,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'expr':([0,5,9,10,11,13,17,],[2,15,19,20,21,27,29,]),'number':([0,5,6,9,10,11,13,16,17,],[4,4,18,4,4,4,4,18,4,]),'exprPow':([12,24,30,31,32,33,36,],[22,34,39,40,41,42,44,]),'numberPow':([12,24,25,30,31,32,33,35,36,],[23,23,37,23,23,23,23,37,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> expr ENDL','line',2,'p_line_expr','yaccrules.py',14),
  ('line -> error ENDL','line',2,'p_line_error','yaccrules.py',22),
  ('expr -> number','expr',1,'p_expr_number','yaccrules.py',32),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_paren','yaccrules.py',39),
  ('expr -> SUB LPAREN expr RPAREN','expr',4,'p_expr_neg','yaccrules.py',43),
  ('expr -> expr ADD expr','expr',3,'p_expr_add','yaccrules.py',49),
  ('expr -> expr SUB expr','expr',3,'p_expr_sub','yaccrules.py',55),
  ('expr -> expr MUL expr','expr',3,'p_expr_mul','yaccrules.py',61),
  ('expr -> expr POW exprPow','expr',3,'p_expr_pow','yaccrules.py',67),
  ('expr -> expr DIV expr','expr',3,'p_expr_div','yaccrules.py',73),
  ('number -> NUM','number',1,'p_number_pos','yaccrules.py',83),
  ('number -> SUB number','number',2,'p_number_neg','yaccrules.py',87),
  ('exprPow -> numberPow','exprPow',1,'p_exprPow_number','yaccrules.py',93),
  ('exprPow -> LPAREN exprPow RPAREN','exprPow',3,'p_exprPow_paren','yaccrules.py',100),
  ('exprPow -> SUB LPAREN exprPow RPAREN','exprPow',4,'p_exprPow_neg','yaccrules.py',104),
  ('exprPow -> exprPow ADD exprPow','exprPow',3,'p_exprPow_add','yaccrules.py',110),
  ('exprPow -> exprPow SUB exprPow','exprPow',3,'p_exprPow_sub','yaccrules.py',116),
  ('exprPow -> exprPow MUL exprPow','exprPow',3,'p_exprPow_mul','yaccrules.py',122),
  ('exprPow -> exprPow DIV exprPow','exprPow',3,'p_exprPow_div','yaccrules.py',128),
  ('numberPow -> NUM','numberPow',1,'p_numberPow_pos','yaccrules.py',138),
  ('numberPow -> SUB numberPow','numberPow',2,'p_numberPow_neg','yaccrules.py',142),
]
