[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.0"

[dependencies]
lalrpop-util = {version = "0.20.0", features = ["lexer", "unicode"]}
num = "0.4.1"
